http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://auth.market-mitra.online/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name

    api-key-auth:
      forwardAuth:
        address: http://api-key-validator:8080/validate
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups